### ISSUE TITLE
Sphinx extension?

### ISSUE THREAD

**Issue by deeplook** [maartenbreddels/ipyvolume#107]
Awesome project!! Any plans for providing (or calling for) a Sphinx extension? Putting this here at least for the record...

**Comment by maartenbreddels** [comment]
Thanks, what should it do actually, what did you have in mind, since it
already renders on rtd using jupyter-sphinx


(from mobile phone)

On 15 Feb 2018 18:17, "deeplook" <notifications@github.com> wrote:

Awesome project!! Any plans for providing a Sphinx extension? Putting this
here at least for the record...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/maartenbreddels/ipyvolume/issues/107>, or mute the
thread

**Comment by deeplook** [comment]
Right. I was not yet much aware of Jupyter-Sphinx bridges, but maybe something also like https://nbsphinx.readthedocs.io could be used, then. But I think in my enthusiasm I was hoping for some more lightweight solution that would not need any Jupyter installation, and could be packaged into some static HTML package (and passed around) with only a bunch of other JS packages added. Something in the same spirit like the Sphinx Graphviz extension (which renders diagrams into static bitmaps, though).

**Comment by deeplook** [comment]
But I realize one needs to execute Python code anyway. At which point my argument likely collapses...

**Comment by maartenbreddels** [comment]
Well, nbsphinx works when jupyter-sphinx to render them on for instance rtd.
Using `ipv.save('bla.html', offline=True/False)` will create a standalone html page and some js files that you can put anywhere, open on your phone (for use with google cardboard for instance). As long as no Python code is needed, everything works. See the bottom example here:
http://ipyvolume.readthedocs.io/en/latest/ for instance.

**Comment by deeplook** [comment]
Cool, I realize I must familiarize myself more with the recent developments in the Jupyter/Sphinx world. Thinks! And put some IBAN somewhere for donations! 😁
