### ISSUE TITLE
What's the best way to get interactive plots that persist when a Jupyter notebook is offline?

### ISSUE THREAD

**Issue by mglerner** [maartenbreddels/ipyvolume#144]
First, thanks for ipyvolume!

In my workflow right now, I do a lot of relatively intensive calculations, the results of which are a 3D plot. I do this in a Jupyter notebook. As far as I can tell (and maybe I'm doing something wrong), if I just use `%matplotlib notebook`, the 3D plot is nice and interactive while I'm in the session that created it. However, if I shutdown the kernel and come back to it, it's just a static plot (or it doesn't show up at all).

Meanwhile, it looks like ipyvolume can make persistent interactive 3D plots for me. As far as I can tell (and, again, maybe I'm doing something wrong), if I just make plots using ipyvolume, I have the same issue (shut down the kernel, reload the notebook, it's just a static plot or doesn't show up at all). However, If I do something like

```python
import ipyvolume as ipv
import ipyvolume.pylab as p3
from IPython.core.display import HTML
x, y, z, u, v = ipv.examples.klein_bottle(draw=False)
ipv.figure()
m = ipv.plot_mesh(x, y, z, wireframe=False)
ipv.squarelim()
ipv.show()
p3.save('./foo.html')
HTML(open('./foo.html').read())
```

then the second plot is interactive when I shut the kernel down and reload the notebook. Finally, my question: is there some way to make that the default behavior? I.e. some way to make it so that, by default, I can still interact with 3D plots if I come back to notebook later and don't want to spend the time necessary to run the analysis?

If not, I'll stick with the above, because it works (thanks!). But I thought I'd ask in case there was something more elegant available.

Thanks!

**Comment by maartenbreddels** [comment]
Thanks Michael,

I have to say that I was amazed by your second solution, creative!
When you don't shutdown the kernel, and reload the page, the widgets should be displayed (in the classical notebook, in jupyter lab this is not supported yet).
When you shutdown the notebook, the widget information is lost, since by default it is not stored in the notebook.
However, if you click in the menu: Widgets-> Save Notebook Widget State, it will save the widget state in the notebook (you can inspect the notebook with less, or see the file size grow to confirm it).
Now you can open it, or render it on nbviewer etc.
Hope it works as advertised!

cheers,

Maarten

**Comment by mglerner** [comment]
That's pretty fantastic! Thanks!

**Comment by maartenbreddels** [comment]
👍 glad I could help
