### ISSUE TITLE
Plot two volumes in one viewer?

### ISSUE THREAD

**Issue by PennyQ** [maartenbreddels/ipyvolume#20]
Hi, is there an easy way to plot two (or more) volumes in one viewer simultaneously? I have some data of Orion cloud but from different component (dust, gas, etc.), I want to have them plotted all at once with `volshow` or `quickvolshow`. Thanks!

**Comment by maartenbreddels** [comment]
Hi Penny,

unfortunately not right now. Having multi volume rendering where the two volumes share exactly the same volume would not require too much work though. This was actually the reason I started to build my own volume rendering in [vaex](http://vaex.astro.rug.nl/). I'm a bit short on time lately, but if I see a chance to do this quickly, I might give it a go. Otherwise if you feel like trying to implement this yourself, I can give you some pointers and help. When the volumes do not fill the same space, it will be a bit more challenging.
Another thing I'd really love to have is isosurface rendering, however this will only be useful I think when transparency is handled, which is a tricky subject.
And I'd love to see that all rendered together!

cheers,

Maarten

**Comment by bocklund** [comment]
@maartenbreddels  Does current limitation hold true for all of ipyvolume (specifically mesh or other surface-style plots)?

**Comment by maartenbreddels** [comment]
Hi,

No, you can mix anything together, but only with 1 volumetric dataset.

cheers,

Maarten

**Comment by maartenbreddels** [comment]
Mulivolume rendering is in, the next release (0.5) should have this.
