### ISSUE TITLE
surface plots

### ISSUE THREAD

**Issue by minrk** [maartenbreddels/ipyvolume#22]
I realize it's called ipyvolume, but what's the scope plan for `ipyvolume.pylab`? Are surface plots in scope? Or lines / contours / etc.? I guess another way of saying it is what subset of [mplot3d](http://matplotlib.org/examples/mplot3d/index.html) would be appropriate to include here?

We're investigating 3D visualization tools in Jupyter, and the situation right now seems to be many tools, each of which solves a different small subset of 3D viz. I'm trying to get a handle on which ones are missing certain features because they are out of scope (and will stay that way), or because they haven't been implemented yet.

**Comment by maartenbreddels** [comment]
With the scatter and quiver, the only-volume-rendering station has passed. Let's re-explain the volume part of the name because the plot is in a '3d volume' :).
Yes, isosurface rendering is one of the things I will need in the future, so that I think will happen. Lines is also something I'd really like to have (but is not so trivial!).
I think mplot3d parity will be a nice goal, and I have no issue with going that direction.
Also including pythreejs will allow for more general object rendering, and also that I see as a possibility. I think the focus for ipyvolume should be (mostly) visualization for scientific purposes, ala matploblib. I hope that answers your question.

My biggest issue with new things is unittesting, it's not set up right now, but should be possible (i've seen people set up testing of threejs).

**Comment by maartenbreddels** [comment]
As mentioned [here](https://github.com/OpenDreamKit/OpenDreamKit/issues/86#issuecomment-298156357) surface plots are being worked on (I initially though you ment isosurface). Simple line rendering is possible, but not yet exposed via the pylab interface.

**Comment by maartenbreddels** [comment]
Will appear in version 0.4.0
