### ISSUE TITLE
Don't use backticks in the javascript code

### ISSUE THREAD

**Issue by SylvainCorlay** [maartenbreddels/ipyvolume#5]
The semver_range template makes use of backtick quotes, which is not supported by IE 11.

**Comment by SylvainCorlay** [comment]
As you want. As per semver, `1.5.7` should be compatible with `1.2.0`

**Comment by maartenbreddels** [comment]
API wise yes, but I can imagine defaults changing, which could break it. And for instance the `.index` vs `.value` issue here https://github.com/ipython/ipywidgets/issues/1091
could also break existing embedded code out there I can imagine.
Any way, you'd limit yourself in what you can change by having ^, with ~ you are a bit more free, and since the last number should be fixes only, I guess ~ fits better.

**Comment by maartenbreddels** [comment]
fixed by 22a90e4391381ca25ca0cad5ae39b8f1b4714014
